utterance/utterances

README.md
=> Add my site

README.md
Utterances is awesome! Why isn't this super popular???
=> Add blog to list

README.md
=> Count me in

README.md
Moved my blog. Sorry for inconvenience! Won't happen again!
=> blog.davvidbaker.com -> davidbaker.is/scribbling

README.md
Added [fdp.io](https://fdp.io) to list of sites using this cool project! One feature request I did have was the ability to have a light/dark theme. The current theme looks great on my light theme but stands out on the dark.
=> Add fdp.io to list of sites using uterrances

README.md
I'm using utterances for the second edition of my “Writing an OS in Rust” blog and it works great! Thanks a lot for your work!
=> Add my “Writing an OS in Rust” blog to the list

package.json, src/_timeline-comment.scss, src/_util.scss, src/client.ts, src/comment-component.ts, src/github.ts, src/index.scss, src/new-comment-component.ts, src/timeline-component.ts, src/utterances.scss, src/utterances.ts, yarn.lock
=> markdown preview

README.md
I actually use it on all three
=> Add all my blogs with utterances

README.md
This is great stuff, sure beats dealing with all the stuff disqus pulls in
=> Add site to list :)

README.md
Great work!  I am using utterances now.
This is my personal blog. Thank you!
=> Added www.xianmin.org to sites using utterances

README.md
Great work! Now there's no need for to worry about GDPR. :laughing: :+1:
=> Added 'philip-trauner.me' to sites using Utterances

src/client.ts, src/index.html
=> prefer canonical url, ignore hash

src/new-comment-component.ts
=> submit when ctrl+enter is pressed

src/_timeline-comment.scss, src/_timeline.scss, src/client.ts, src/index.scss
=> enable customizing width

README.md
Thanks so much for utteranc.es; it works really well!
=> add blog to list of sites using utterances

src/stylesheets/timeline-comment.scss, src/stylesheets/util.scss
=> reset safari input appearance

src/client.ts
without escape, `utterancZes` also matches.
=> escape dot in regex

src/comment-component.ts, src/stylesheets/email-fragment.scss, src/stylesheets/utterances.scss
=> implement email fragments

SITES.md
I dreamed of it, you did it, congrats !
=> site using Utterances: add lisp-journey

SITES.md
Thanks for the work with this tool! Looks great
=> Add swifttalking.com to the sites list

src/configuration-component.ts, src/github.ts, src/index.html, src/page-attributes.ts, src/utterances.ts
=> label support

src/authorized.html, src/authorized.ts, src/oauth.ts, src/utterances.ts
=> keep auth flow in same tab

src/github.ts, src/stylesheets/timeline.scss, src/stylesheets/util.scss, src/stylesheets/utterances.scss, src/stylesheets/zigzag.scss, src/timeline-component.ts, src/utterances.ts
=> pagination support

SITES.md
- Add my website to SITES.md (kiedtl.surge.sh)
BTW I've noticed that many of the websites in the list are defunct or have disappeared. Some of them, like **danyow.net**, are 404'ing for me.
=> Add my website

src/reactions.ts
=> schedule measure after submitting reaction

src/stylesheets/themes/dark-blue/button.scss, src/stylesheets/themes/dark-blue/index.scss, src/stylesheets/themes/dark-blue/syntax.scss, src/stylesheets/themes/dark-blue/utterances.scss, src/stylesheets/themes/dark-blue/variables.scss
Adds a Dark Blue theme to be used on my website
=> Dark Blue theme for my website

SITES.md
Added blog.ronjdias.com to the list of websites that use this awesome commenting tool.
=> Added Site to list

SITES.md
Added "Sample Space" to the list of sites using utterances.
=> Added "Sample Space".

SITES.md
=> Added mine

SITES.md
=> Add R-hub blog

src/github.ts
=> use best title match, then fallback to first match

src/client.ts, src/comment-component.ts, src/deparam.ts, src/github.ts, src/new-comment-component.ts, src/reactions.ts
This PR will
* remove `any`
* use `Record`
=> fix: Remove any and use Record

package.json, src/client.ts, src/oauth.ts, src/page-attributes.ts, yarn.lock
=> workaround third-party cookie blocking

SITES.md
=> Add masalmon.eu to list of sites

SITES.md
my site(https://sathnaga86.com/) comment section is powered by utteranc.es, let's update here to
reflect the same.
=> Update my site link

SITES.md
Hi,
Your commenting software is great! I got it up and running very quickly, looks awesome and just works. Could you please add my site to the list of sites that use it?
Thanks!
=> Add Forest Hex to sites list.

SITES.md
Add https://niemannross.com/link/stupidmachine - a murder mystery solved by a refrigerator
=> Add stupid machine

PRIVACY-POLICY.md
Fixes #185
Restores and updates the privacy policy
=> Fix privacy policy

SITES.md
=> Added utterances to my site

SITES.md
Using utterances in the blog posts
=> Add marttcw.github.io to the list

SITES.md
Hello,
this adds a new site to the list.
Thanks for utteranc.es!
=> add christianfei.com to SITES.md

src/comment-component.ts, src/timeline-component.ts
=> lock reactions when issue is locked

SITES.md
I'm currently using Utterances on my site's blog, I really love this project!
=> Added Alain.xyz to SITES.md

SITES.md
Now using utterances for the blog comments. An example post [here](https://www.abhith.net/blog/azure-devops-build-could-not-locate-the-assembly/).
Previously was using Disqus. Now in ❤️ with utterances.
=> Add abhith.net to SITES.md

SITES.md
=> +1 site :)

SITES.md
Another blog using this wonderful tool
=> Added pragmatic-coder.net

SITES.md
I just decided to set it up for my [personal site](https://rgoswami.me) and thought I might add myself.
=> sites: Update to add self

SITES.md
Thank you for this amazing project!
=> Efe Öge's blog is added to the SITES.md

SITES.md
=> add my website to the list

src/client.ts, src/new-comment-component.ts
=> fix 414 and accessibility bug

src/new-comment-component.ts
as requested here: https://github.com/utterance/utterances/issues/304#issuecomment-624414930
=> change nav to div per request

SITES.md
See https://github.com/wei2912/blog-src/commit/75bcaeb3d999481055f1f4cd1891d92a9312e0cc
The work here is commendable, the setup was extremely smooth for me and took barely a minute. :)
=> Add weien.io to SITES.md

SITES.md
Add  the link of colynn's blog into  `SITES.md`
Nothing conflict.
I hope you accept this pull request. 
thanks for your time.
=> add colynn's blog links

src/client.ts, src/configuration-component.ts, src/preferred-theme.ts
=> Add prefers-color-scheme theme

SITES.md
The blog domain has been updated.
=> Update U.Cor to ./kwaa.dev

src/client.ts
Lazy loads the utterances iframe
=> Add loading="lazy" to iframe

src/github.ts
Close https://github.com/utterance/utterances/issues/470
I didn't read all the sources. Searching shows this is the only place that needs to be changed.
=> always add authorization token when available

SITES.md
removed space so it used correct markdown syntax
=> fix markdown
